<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Infrastructure\**" />
    <EmbeddedResource Remove="Infrastructure\**" />
    <None Remove="Infrastructure\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="BLL\alarm_id_for_cut.cs" />
    <Compile Remove="BLL\alarm_level.cs" />
    <Compile Remove="BLL\alarm_record.cs" />
    <Compile Remove="BLL\alarm_rule.cs" />
    <Compile Remove="BLL\alarm_temp.cs" />
    <Compile Remove="BLL\device_alarm.cs" />
    <Compile Remove="BLL\device_alert_config.cs" />
    <Compile Remove="BLL\device_andon_record.cs" />
    <Compile Remove="BLL\device_andon_temp.cs" />
    <Compile Remove="BLL\device_childeqcode.cs" />
    <Compile Remove="BLL\device_config.cs" />
    <Compile Remove="BLL\device_inputoutput.cs" />
    <Compile Remove="BLL\device_inputoutput_config.cs" />
    <Compile Remove="BLL\device_inputoutput_data.cs" />
    <Compile Remove="BLL\device_instation_data.cs" />
    <Compile Remove="BLL\device_materialinfo_record.cs" />
    <Compile Remove="BLL\device_md_data.cs" />
    <Compile Remove="BLL\device_production.cs" />
    <Compile Remove="BLL\device_production_data.cs" />
    <Compile Remove="BLL\device_spart.cs" />
    <Compile Remove="BLL\device_spart_config.cs" />
    <Compile Remove="BLL\device_tag.cs" />
    <Compile Remove="BLL\device_weight_data.cs" />
    <Compile Remove="BLL\input_log_from.cs" />
    <Compile Remove="BLL\input_variable_history.cs" />
    <Compile Remove="BLL\log_level.cs" />
    <Compile Remove="BLL\log_mes_interface_paramvalue.cs" />
    <Compile Remove="BLL\log_mes_interface_temp.cs" />
    <Compile Remove="BLL\log_mes_interface_weight.cs" />
    <Compile Remove="BLL\log_operation.cs" />
    <Compile Remove="BLL\ng_code.cs" />
    <Compile Remove="BLL\plc_area_config.cs" />
    <Compile Remove="BLL\plc_brand.cs" />
    <Compile Remove="BLL\plc_protocol.cs" />
    <Compile Remove="BLL\plc_rw_field.cs" />
    <Compile Remove="BLL\production_status.cs" />
    <Compile Remove="BLL\user_define_config.cs" />
    <Compile Remove="BLL\user_define_data.cs" />
    <Compile Remove="BLL\user_define_module.cs" />
    <Compile Remove="BLL\user_define_variable_data.cs" />
    <Compile Remove="BLL\value_types.cs" />
    <Compile Remove="BLL\variable_type.cs" />
    <Compile Remove="DAL\alarm_id_for_cut.cs" />
    <Compile Remove="DAL\alarm_level.cs" />
    <Compile Remove="DAL\alarm_record.cs" />
    <Compile Remove="DAL\alarm_rule.cs" />
    <Compile Remove="DAL\alarm_temp.cs" />
    <Compile Remove="DAL\device_alarm.cs" />
    <Compile Remove="DAL\device_alert_config.cs" />
    <Compile Remove="DAL\device_andon_record.cs" />
    <Compile Remove="DAL\device_andon_temp.cs" />
    <Compile Remove="DAL\device_childeqcode.cs" />
    <Compile Remove="DAL\device_config.cs" />
    <Compile Remove="DAL\device_inputoutput.cs" />
    <Compile Remove="DAL\device_inputoutput_config.cs" />
    <Compile Remove="DAL\device_inputoutput_data.cs" />
    <Compile Remove="DAL\device_instation_data.cs" />
    <Compile Remove="DAL\device_materialinfo_record.cs" />
    <Compile Remove="DAL\device_md_data.cs" />
    <Compile Remove="DAL\device_production.cs" />
    <Compile Remove="DAL\device_production_data.cs" />
    <Compile Remove="DAL\device_spart.cs" />
    <Compile Remove="DAL\device_spart_config.cs" />
    <Compile Remove="DAL\device_tag.cs" />
    <Compile Remove="DAL\device_weight_data.cs" />
    <Compile Remove="DAL\input_log_from.cs" />
    <Compile Remove="DAL\input_variable_history.cs" />
    <Compile Remove="DAL\log_level.cs" />
    <Compile Remove="DAL\log_mes_interface_paramvalue.cs" />
    <Compile Remove="DAL\log_mes_interface_temp.cs" />
    <Compile Remove="DAL\log_mes_interface_weight.cs" />
    <Compile Remove="DAL\log_operation.cs" />
    <Compile Remove="DAL\ng_code.cs" />
    <Compile Remove="DAL\plc_area_config.cs" />
    <Compile Remove="DAL\plc_brand.cs" />
    <Compile Remove="DAL\plc_protocol.cs" />
    <Compile Remove="DAL\plc_rw_field.cs" />
    <Compile Remove="DAL\production_status.cs" />
    <Compile Remove="DAL\user_define_config.cs" />
    <Compile Remove="DAL\user_define_data.cs" />
    <Compile Remove="DAL\user_define_module.cs" />
    <Compile Remove="DAL\user_define_variable_data.cs" />
    <Compile Remove="DAL\value_types.cs" />
    <Compile Remove="DAL\variable_type.cs" />
    <Compile Remove="DBUtility\DbHelperDapper.cs" />
    <Compile Remove="DBUtility\DbHelperOleDb.cs" />
    <Compile Remove="DBUtility\DbHelperSQL.cs" />
    <Compile Remove="DBUtility\DbHelperSQLP.cs" />
    <Compile Remove="Model\alarm_id_for_cut.cs" />
    <Compile Remove="Model\alarm_level.cs" />
    <Compile Remove="Model\alarm_record.cs" />
    <Compile Remove="Model\alarm_rule.cs" />
    <Compile Remove="Model\alarm_temp.cs" />
    <Compile Remove="Model\device _alarm.cs" />
    <Compile Remove="Model\device _config.cs" />
    <Compile Remove="Model\device_alert_config.cs" />
    <Compile Remove="Model\device_andon_record.cs" />
    <Compile Remove="Model\device_andon_temp.cs" />
    <Compile Remove="Model\device_childeqcode.cs" />
    <Compile Remove="Model\device_inputoutput.cs" />
    <Compile Remove="Model\device_inputoutput_config.cs" />
    <Compile Remove="Model\device_inputoutput_data.cs" />
    <Compile Remove="Model\device_instation_data.cs" />
    <Compile Remove="Model\device_materialinfo_record.cs" />
    <Compile Remove="Model\device_md_data.cs" />
    <Compile Remove="Model\device_production.cs" />
    <Compile Remove="Model\device_production_data.cs" />
    <Compile Remove="Model\device_spart.cs" />
    <Compile Remove="Model\device_spart_config.cs" />
    <Compile Remove="Model\device_tag.cs" />
    <Compile Remove="Model\device_weight_data.cs" />
    <Compile Remove="Model\input_log_from.cs" />
    <Compile Remove="Model\input_variable_history.cs" />
    <Compile Remove="Model\log_level.cs" />
    <Compile Remove="Model\log_mes_interface_paramvalue.cs" />
    <Compile Remove="Model\log_mes_interface_temp.cs" />
    <Compile Remove="Model\log_mes_interface_weight.cs" />
    <Compile Remove="Model\log_operation.cs" />
    <Compile Remove="Model\ng_code.cs" />
    <Compile Remove="Model\plc_area_config.cs" />
    <Compile Remove="Model\plc_brand.cs" />
    <Compile Remove="Model\plc_protocol.cs" />
    <Compile Remove="Model\plc_rw_field.cs" />
    <Compile Remove="Model\production_status.cs" />
    <Compile Remove="Model\user_define_config.cs" />
    <Compile Remove="Model\user_define_data.cs" />
    <Compile Remove="Model\user_define_module.cs" />
    <Compile Remove="Model\user_define_variable_data.cs" />
    <Compile Remove="Model\value_types.cs" />
    <Compile Remove="Model\variable_type.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.0.2" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="9.0.7" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.7" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.7" />
    <PackageReference Include="MySql.Data" Version="9.4.0" />
    <PackageReference Include="System.Data.OleDb" Version="9.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SUNWODA_SEVB.Core\SUNWODA_SEVB.Core.csproj" />
    <ProjectReference Include="..\SUNWODA_SEVB.Logging\SUNWODA_SEVB.Logging.csproj" />
  </ItemGroup>

</Project>
