//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//
//     对此文件的更改可能导致不正确的行为，并在以下条件下丢失:
//     代码重新生成。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTOMESWebService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PTOMESWebService.MESInterfaceSoap")]
    public interface MESInterfaceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AGetVersion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> AGetVersionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LockProduct", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> LockProductAsync(string product, string moNumber, string userCode, string errorItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PackLinkCellGroup1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> PackLinkCellGroup1Async(string Pack_Sn, string Cell_Sn, string user_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PackLinkCellGroup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> PackLinkCellGroupAsync(string Pack_Sn, string Cell_Sn, string M_MO, string M_MACHINENO, string M_KP_ITEMSN_ALL, string user_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCurShipmentNo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetCurShipmentNoAsync(string ShipmentInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StartProduction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> StartProductionAsync(string ProductionInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckItem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> CheckItemAsync(string ItemInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CellBOMItemsCheck", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> CellBOMItemsCheckAsync(string M_SN, string M_MO, string M_USERNO, string M_MACHINENO, string M_KP_ITEMSN_ALL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProductionGroupInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> ProductionGroupInfoAsync(string strParameterInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BOMItemsCheck", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> BOMItemsCheckAsync(string M_SN, string M_MO, string M_USERNO, string M_MACHINENO, string M_KP_ITEMSN_ALL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ItemsGroupCheck", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> ItemsGroupCheckAsync(string M_MO, string M_MACHINENO, string M_KP_ITEM, string M_KP_ITEM_LOT);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckUserRole", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> CheckUserRoleAsync(string M_USERNO, string M_PASSWORD, string M_RoleName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GroupNameCheck", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GroupNameCheckAsync(string MainSN, string GroupName, string MO, string Process, string Userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeviecStatusInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> DeviecStatusInfoAsync(string deviecCode, string deviecStatus, string StartTime, string EndTime, string deviecErrorInfo, string userCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckUserDo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> CheckUserDoAsync(string M_USERNO, string M_PASSWORD, string M_MACHINENO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveXRAYData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> SaveXRAYDataAsync(string product_sn, string emp_no, string test_data, string test_result, string pic_path, string machine_no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FTPSaveXRAYData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> FTPSaveXRAYDataAsync(string product_sn, string emp_no, string test_data, string test_result, string pic_path, string machine_no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GroupTest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GroupTestAsync(string M_SN, string M_MACHINCENO, string M_EMP, string MoNumber, string GroupName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CellGroupLink", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> CellGroupLinkAsync(string cell_list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestDataLogs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task TestDataLogsAsync(string ProductSn, string strResult, string OperatorID, string GroupCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestDataGroupInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> TestDataGroupInfoAsync(string GroupInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WIPTEST", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> WIPTESTAsync(string M_SN, string M_RESULT, string M_USERNO, string M_MACHINENO, string M_ERROR, string M_ITEMVALUE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckProductMoNumber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> CheckProductMoNumberAsync(string product, string moNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CellCoverInput", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> CellCoverInputAsync(string M_SN, string M_MO, string M_USERNO, string M_MACHINENO, string M_KP_ITEMSN_ALL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExecuteNonQuery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> ExecuteNonQueryAsync(string sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSqlData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<PTOMESWebService.GetSqlDataResponseGetSqlDataResult> GetSqlDataAsync(string sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExecuteNonQueryConn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> ExecuteNonQueryConnAsync(string sql, string Conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HWInterface", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> HWInterfaceAsync(string M_MACHINENO, string M_PRODUCT_SN, string M_MO, string M_EMP, string M_KP_ITEMSN_ALL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SNbindBatchNumber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> SNbindBatchNumberAsync(string MainSN, string Z_BatchSN, string F_BatchSN, string MachineNo, string Userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OCVTestData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> OCVTestDataAsync(PTOMESWebService.TestDataGroupInfoNEW TestDataInfoObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWeightBeforeInjectionA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetWeightBeforeInjectionAAsync(string ProductSn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWeightBeforeInjectionB", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetWeightBeforeInjectionBAsync(string ProductSn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWeightBeforeInjectionC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetWeightBeforeInjectionCAsync(string ProductSn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOCVData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetOCVDataAsync(string ProductSn, string num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/checkNetStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> checkNetStatusAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OfflineDataUpload", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> OfflineDataUploadAsync(string M_SN, string M_RESULT, string M_USERNO, string M_MACHINENO, string M_ERROR, string M_ITEMVALUE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddGongBoard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> AddGongBoardAsync(string GroupInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginCheck", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> LoginCheckAsync(string loginInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MaterialControl", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> MaterialControlAsync(string modelStr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InStationCheck", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> InStationCheckAsync(string modelStr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OutStationCheckData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> OutStationCheckDataAsync(string modelStr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubProductBinding", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> SubProductBindingAsync(string modelStr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubProductBindingCheck", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> SubProductBindingCheckAsync(string modelStr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProductBinding", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> ProductBindingAsync(string modelStr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SidePanelMountingMore", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> SidePanelMountingMoreAsync(string modelStr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FittingBinding", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> FittingBindingAsync(string modelStr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FittingUnBinding", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> FittingUnBindingAsync(string modelStr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBoardBarcode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetBoardBarcodeAsync(string modelStr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CellGroupCheck", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> CellGroupCheckAsync(string modelStr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CellGroupLinkCheck", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> CellGroupLinkCheckAsync(string cell_sn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckPackSNBeforeBindAndConversion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> CheckPackSNBeforeBindAndConversionAsync(string M_PRODUCT_SN, string M_MO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CollectFixureUseTimes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> CollectFixureUseTimesAsync(string M_MACHINENO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelSN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> DelSNAsync(string M_SN, string M_EMP_NO, string M_EMP_PWD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CellBatchInsertData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> CellBatchInsertDataAsync(PTOMESWebService.CellBatchInsertDataDT dt, string table_name, int batch_count, string sqlconn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoCapacity", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> AutoCapacityAsync(string GroupInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BarcodeConversion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> BarcodeConversionAsync(string M_PRODUCT_SN, string M_CUSTOMER_SN, string M_MO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BatchInsertData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> BatchInsertDataAsync(PTOMESWebService.BatchInsertDataDT dt, string table_name, int batch_count, string sqlconn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCellGroupPack", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetCellGroupPackAsync(string pack_sn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFluidLoss", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetFluidLossAsync(string strBattrrySN);
        
        // CODEGEN: 正在生成消息协定，因为操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOCV3", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<PTOMESWebService.GetOCV3Response> GetOCV3Async(PTOMESWebService.GetOCV3Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPDAInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetPDAInfoAsync(string PDAInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductEndDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetProductEndDateAsync(string product_sn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductSN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetProductSNAsync(string BATTERIESNO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductTestDatas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetProductTestDatasAsync(string lastFlag, string product_sn, string testitems);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSqlDataConn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<PTOMESWebService.GetSqlDataConnResponseGetSqlDataConnResult> GetSqlDataConnAsync(string sql, string conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HR_UserInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> HR_UserInfoAsync(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HWInterfaceTest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> HWInterfaceTestAsync(string M_MACHINENO, string M_PRODUCT_SN, string M_MO, string M_EMP, string M_KP_ITEMSN_ALL, string M_ITEMVALUE, string M_RESULT, string M_ERROR);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OfflineData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> OfflineDataAsync(string M_SN, string M_RESULT, string M_USERNO, string M_MACHINENO, string M_ERROR, string M_ITEMVALUE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SMTImageUpload_XRAY", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> SMTImageUpload_XRAYAsync(string filename, string img_path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestDataDimension", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> TestDataDimensionAsync(string M_SN, string M_RESULT, string M_USERNO, string M_MACHINENO, string M_ERROR, string M_ITEMVALUE, string M_MO, string M_GROUP_CODE, string M_LOT);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WeldInput", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> WeldInputAsync(string M_SN, string M_MO, string M_USERNO, string M_MACHINENO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSystemTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> getSystemTimeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UnBindDingTray", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> UnBindDingTrayAsync(string trayNo, string userCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BindDingTray", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> BindDingTrayAsync(string jsonData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckTrayValid", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> CheckTrayValidAsync(string trayNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProducdtUnBinding", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> ProducdtUnBindingAsync(string jsonData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CellGroupUnBinding", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> CellGroupUnBindingAsync(string trayNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFormulaInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetFormulaInfoAsync(string modelStr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGroupName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetGroupNameAsync(string productSnList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MoNumberAndGroupTest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> MoNumberAndGroupTestAsync(string M_MACHINCENO, string M_EMP, string CellSn, string ProductSn, string GroupName, string MoNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CellGroupLink1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> CellGroupLink1Async(string CellInfo);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class GetSqlDataResponseGetSqlDataResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class StepDataInfo
    {
        
        private string stepField;
        
        private string stepNameField;
        
        private string startDateField;
        
        private string endDateField;
        
        private string startVoltageField;
        
        private string endVoltageField;
        
        private string capacityField;
        
        private string testTimeField;
        
        private string startTemperatureField;
        
        private string endTemperatureField;
        
        private string currentField;
        
        private string negativeVoltageField;
        
        private string markingField;
        
        private string energyField;
        
        private string channelField;
        
        private string value1Field;
        
        private string value2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Step
        {
            get
            {
                return this.stepField;
            }
            set
            {
                this.stepField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StepName
        {
            get
            {
                return this.stepNameField;
            }
            set
            {
                this.stepNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string StartDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string EndDate
        {
            get
            {
                return this.endDateField;
            }
            set
            {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string StartVoltage
        {
            get
            {
                return this.startVoltageField;
            }
            set
            {
                this.startVoltageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string EndVoltage
        {
            get
            {
                return this.endVoltageField;
            }
            set
            {
                this.endVoltageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Capacity
        {
            get
            {
                return this.capacityField;
            }
            set
            {
                this.capacityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string TestTime
        {
            get
            {
                return this.testTimeField;
            }
            set
            {
                this.testTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string StartTemperature
        {
            get
            {
                return this.startTemperatureField;
            }
            set
            {
                this.startTemperatureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string EndTemperature
        {
            get
            {
                return this.endTemperatureField;
            }
            set
            {
                this.endTemperatureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Current
        {
            get
            {
                return this.currentField;
            }
            set
            {
                this.currentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string NegativeVoltage
        {
            get
            {
                return this.negativeVoltageField;
            }
            set
            {
                this.negativeVoltageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Marking
        {
            get
            {
                return this.markingField;
            }
            set
            {
                this.markingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Energy
        {
            get
            {
                return this.energyField;
            }
            set
            {
                this.energyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Channel
        {
            get
            {
                return this.channelField;
            }
            set
            {
                this.channelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Value1
        {
            get
            {
                return this.value1Field;
            }
            set
            {
                this.value1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Value2
        {
            get
            {
                return this.value2Field;
            }
            set
            {
                this.value2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MaterialInfo
    {
        
        private string materialNoField;
        
        private string materialLotField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MaterialNo
        {
            get
            {
                return this.materialNoField;
            }
            set
            {
                this.materialNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MaterialLot
        {
            get
            {
                return this.materialLotField;
            }
            set
            {
                this.materialLotField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TestDataInfo
    {
        
        private string itemCodeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ItemCode
        {
            get
            {
                return this.itemCodeField;
            }
            set
            {
                this.itemCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TestDataGroupInfoNEW
    {
        
        private string groupCodeField;
        
        private string groupNameField;
        
        private string machineIDField;
        
        private string timeStampField;
        
        private string operatorIDField;
        
        private string productSnField;
        
        private string moNumberField;
        
        private TestDataInfo[] testDataField;
        
        private MaterialInfo[] materialField;
        
        private string testResultField;
        
        private string testReasonField;
        
        private string productModelField;
        
        private string testIdField;
        
        private string z_ShipmentNoField;
        
        private string f_ShipmentNoField;
        
        private string[] cellGroupField;
        
        private StepDataInfo[] stepDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string GroupCode
        {
            get
            {
                return this.groupCodeField;
            }
            set
            {
                this.groupCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string GroupName
        {
            get
            {
                return this.groupNameField;
            }
            set
            {
                this.groupNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MachineID
        {
            get
            {
                return this.machineIDField;
            }
            set
            {
                this.machineIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TimeStamp
        {
            get
            {
                return this.timeStampField;
            }
            set
            {
                this.timeStampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string OperatorID
        {
            get
            {
                return this.operatorIDField;
            }
            set
            {
                this.operatorIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ProductSn
        {
            get
            {
                return this.productSnField;
            }
            set
            {
                this.productSnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string MoNumber
        {
            get
            {
                return this.moNumberField;
            }
            set
            {
                this.moNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        public TestDataInfo[] TestData
        {
            get
            {
                return this.testDataField;
            }
            set
            {
                this.testDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=8)]
        public MaterialInfo[] Material
        {
            get
            {
                return this.materialField;
            }
            set
            {
                this.materialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string TestResult
        {
            get
            {
                return this.testResultField;
            }
            set
            {
                this.testResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string TestReason
        {
            get
            {
                return this.testReasonField;
            }
            set
            {
                this.testReasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ProductModel
        {
            get
            {
                return this.productModelField;
            }
            set
            {
                this.productModelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string TestId
        {
            get
            {
                return this.testIdField;
            }
            set
            {
                this.testIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Z_ShipmentNo
        {
            get
            {
                return this.z_ShipmentNoField;
            }
            set
            {
                this.z_ShipmentNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string F_ShipmentNo
        {
            get
            {
                return this.f_ShipmentNoField;
            }
            set
            {
                this.f_ShipmentNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=15)]
        public string[] CellGroup
        {
            get
            {
                return this.cellGroupField;
            }
            set
            {
                this.cellGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=16)]
        public StepDataInfo[] StepData
        {
            get
            {
                return this.stepDataField;
            }
            set
            {
                this.stepDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class CellBatchInsertDataDT
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class BatchInsertDataDT
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOCV3", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetOCV3Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Machine_NO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string M_SN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string MO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string OCV_Val;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string OCV_Time;
        
        public GetOCV3Request()
        {
        }
        
        public GetOCV3Request(string Machine_NO, string M_SN, string MO, string OCV_Val, string OCV_Time)
        {
            this.Machine_NO = Machine_NO;
            this.M_SN = M_SN;
            this.MO = MO;
            this.OCV_Val = OCV_Val;
            this.OCV_Time = OCV_Time;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOCV3Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetOCV3Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetOCV3Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string OCV_Val;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string OCV_Time;
        
        public GetOCV3Response()
        {
        }
        
        public GetOCV3Response(string GetOCV3Result, string OCV_Val, string OCV_Time)
        {
            this.GetOCV3Result = GetOCV3Result;
            this.OCV_Val = OCV_Val;
            this.OCV_Time = OCV_Time;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class GetSqlDataConnResponseGetSqlDataConnResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface MESInterfaceSoapChannel : PTOMESWebService.MESInterfaceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class MESInterfaceSoapClient : System.ServiceModel.ClientBase<PTOMESWebService.MESInterfaceSoap>, PTOMESWebService.MESInterfaceSoap
    {
        
        /// <summary>
        /// 实现此分部方法，配置服务终结点。
        /// </summary>
        /// <param name="serviceEndpoint">要配置的终结点</param>
        /// <param name="clientCredentials">客户端凭据</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MESInterfaceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(MESInterfaceSoapClient.GetBindingForEndpoint(endpointConfiguration), MESInterfaceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MESInterfaceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MESInterfaceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MESInterfaceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MESInterfaceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MESInterfaceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> AGetVersionAsync()
        {
            return base.Channel.AGetVersionAsync();
        }
        
        public System.Threading.Tasks.Task<string> LockProductAsync(string product, string moNumber, string userCode, string errorItem)
        {
            return base.Channel.LockProductAsync(product, moNumber, userCode, errorItem);
        }
        
        public System.Threading.Tasks.Task<string> PackLinkCellGroup1Async(string Pack_Sn, string Cell_Sn, string user_code)
        {
            return base.Channel.PackLinkCellGroup1Async(Pack_Sn, Cell_Sn, user_code);
        }
        
        public System.Threading.Tasks.Task<string> PackLinkCellGroupAsync(string Pack_Sn, string Cell_Sn, string M_MO, string M_MACHINENO, string M_KP_ITEMSN_ALL, string user_code)
        {
            return base.Channel.PackLinkCellGroupAsync(Pack_Sn, Cell_Sn, M_MO, M_MACHINENO, M_KP_ITEMSN_ALL, user_code);
        }
        
        public System.Threading.Tasks.Task<string> GetCurShipmentNoAsync(string ShipmentInfo)
        {
            return base.Channel.GetCurShipmentNoAsync(ShipmentInfo);
        }
        
        public System.Threading.Tasks.Task<string> StartProductionAsync(string ProductionInfo)
        {
            return base.Channel.StartProductionAsync(ProductionInfo);
        }
        
        public System.Threading.Tasks.Task<string> CheckItemAsync(string ItemInfo)
        {
            return base.Channel.CheckItemAsync(ItemInfo);
        }
        
        public System.Threading.Tasks.Task<string> CellBOMItemsCheckAsync(string M_SN, string M_MO, string M_USERNO, string M_MACHINENO, string M_KP_ITEMSN_ALL)
        {
            return base.Channel.CellBOMItemsCheckAsync(M_SN, M_MO, M_USERNO, M_MACHINENO, M_KP_ITEMSN_ALL);
        }
        
        public System.Threading.Tasks.Task<string> ProductionGroupInfoAsync(string strParameterInfo)
        {
            return base.Channel.ProductionGroupInfoAsync(strParameterInfo);
        }
        
        public System.Threading.Tasks.Task<string> BOMItemsCheckAsync(string M_SN, string M_MO, string M_USERNO, string M_MACHINENO, string M_KP_ITEMSN_ALL)
        {
            return base.Channel.BOMItemsCheckAsync(M_SN, M_MO, M_USERNO, M_MACHINENO, M_KP_ITEMSN_ALL);
        }
        
        public System.Threading.Tasks.Task<string> ItemsGroupCheckAsync(string M_MO, string M_MACHINENO, string M_KP_ITEM, string M_KP_ITEM_LOT)
        {
            return base.Channel.ItemsGroupCheckAsync(M_MO, M_MACHINENO, M_KP_ITEM, M_KP_ITEM_LOT);
        }
        
        public System.Threading.Tasks.Task<string> CheckUserRoleAsync(string M_USERNO, string M_PASSWORD, string M_RoleName)
        {
            return base.Channel.CheckUserRoleAsync(M_USERNO, M_PASSWORD, M_RoleName);
        }
        
        public System.Threading.Tasks.Task<string> GroupNameCheckAsync(string MainSN, string GroupName, string MO, string Process, string Userid)
        {
            return base.Channel.GroupNameCheckAsync(MainSN, GroupName, MO, Process, Userid);
        }
        
        public System.Threading.Tasks.Task<string> DeviecStatusInfoAsync(string deviecCode, string deviecStatus, string StartTime, string EndTime, string deviecErrorInfo, string userCode)
        {
            return base.Channel.DeviecStatusInfoAsync(deviecCode, deviecStatus, StartTime, EndTime, deviecErrorInfo, userCode);
        }
        
        public System.Threading.Tasks.Task<string> CheckUserDoAsync(string M_USERNO, string M_PASSWORD, string M_MACHINENO)
        {
            return base.Channel.CheckUserDoAsync(M_USERNO, M_PASSWORD, M_MACHINENO);
        }
        
        public System.Threading.Tasks.Task<string> SaveXRAYDataAsync(string product_sn, string emp_no, string test_data, string test_result, string pic_path, string machine_no)
        {
            return base.Channel.SaveXRAYDataAsync(product_sn, emp_no, test_data, test_result, pic_path, machine_no);
        }
        
        public System.Threading.Tasks.Task<string> FTPSaveXRAYDataAsync(string product_sn, string emp_no, string test_data, string test_result, string pic_path, string machine_no)
        {
            return base.Channel.FTPSaveXRAYDataAsync(product_sn, emp_no, test_data, test_result, pic_path, machine_no);
        }
        
        public System.Threading.Tasks.Task<string> GroupTestAsync(string M_SN, string M_MACHINCENO, string M_EMP, string MoNumber, string GroupName)
        {
            return base.Channel.GroupTestAsync(M_SN, M_MACHINCENO, M_EMP, MoNumber, GroupName);
        }
        
        public System.Threading.Tasks.Task<string> CellGroupLinkAsync(string cell_list)
        {
            return base.Channel.CellGroupLinkAsync(cell_list);
        }
        
        public System.Threading.Tasks.Task TestDataLogsAsync(string ProductSn, string strResult, string OperatorID, string GroupCode)
        {
            return base.Channel.TestDataLogsAsync(ProductSn, strResult, OperatorID, GroupCode);
        }
        
        public System.Threading.Tasks.Task<string> TestDataGroupInfoAsync(string GroupInfo)
        {
            return base.Channel.TestDataGroupInfoAsync(GroupInfo);
        }
        
        public System.Threading.Tasks.Task<string> WIPTESTAsync(string M_SN, string M_RESULT, string M_USERNO, string M_MACHINENO, string M_ERROR, string M_ITEMVALUE)
        {
            return base.Channel.WIPTESTAsync(M_SN, M_RESULT, M_USERNO, M_MACHINENO, M_ERROR, M_ITEMVALUE);
        }
        
        public System.Threading.Tasks.Task<string> CheckProductMoNumberAsync(string product, string moNumber)
        {
            return base.Channel.CheckProductMoNumberAsync(product, moNumber);
        }
        
        public System.Threading.Tasks.Task<string> CellCoverInputAsync(string M_SN, string M_MO, string M_USERNO, string M_MACHINENO, string M_KP_ITEMSN_ALL)
        {
            return base.Channel.CellCoverInputAsync(M_SN, M_MO, M_USERNO, M_MACHINENO, M_KP_ITEMSN_ALL);
        }
        
        public System.Threading.Tasks.Task<string> ExecuteNonQueryAsync(string sql)
        {
            return base.Channel.ExecuteNonQueryAsync(sql);
        }
        
        public System.Threading.Tasks.Task<PTOMESWebService.GetSqlDataResponseGetSqlDataResult> GetSqlDataAsync(string sql)
        {
            return base.Channel.GetSqlDataAsync(sql);
        }
        
        public System.Threading.Tasks.Task<string> ExecuteNonQueryConnAsync(string sql, string Conn)
        {
            return base.Channel.ExecuteNonQueryConnAsync(sql, Conn);
        }
        
        public System.Threading.Tasks.Task<string> HWInterfaceAsync(string M_MACHINENO, string M_PRODUCT_SN, string M_MO, string M_EMP, string M_KP_ITEMSN_ALL)
        {
            return base.Channel.HWInterfaceAsync(M_MACHINENO, M_PRODUCT_SN, M_MO, M_EMP, M_KP_ITEMSN_ALL);
        }
        
        public System.Threading.Tasks.Task<string> SNbindBatchNumberAsync(string MainSN, string Z_BatchSN, string F_BatchSN, string MachineNo, string Userid)
        {
            return base.Channel.SNbindBatchNumberAsync(MainSN, Z_BatchSN, F_BatchSN, MachineNo, Userid);
        }
        
        public System.Threading.Tasks.Task<string> OCVTestDataAsync(PTOMESWebService.TestDataGroupInfoNEW TestDataInfoObj)
        {
            return base.Channel.OCVTestDataAsync(TestDataInfoObj);
        }
        
        public System.Threading.Tasks.Task<string> GetWeightBeforeInjectionAAsync(string ProductSn)
        {
            return base.Channel.GetWeightBeforeInjectionAAsync(ProductSn);
        }
        
        public System.Threading.Tasks.Task<string> GetWeightBeforeInjectionBAsync(string ProductSn)
        {
            return base.Channel.GetWeightBeforeInjectionBAsync(ProductSn);
        }
        
        public System.Threading.Tasks.Task<string> GetWeightBeforeInjectionCAsync(string ProductSn)
        {
            return base.Channel.GetWeightBeforeInjectionCAsync(ProductSn);
        }
        
        public System.Threading.Tasks.Task<string> GetOCVDataAsync(string ProductSn, string num)
        {
            return base.Channel.GetOCVDataAsync(ProductSn, num);
        }
        
        public System.Threading.Tasks.Task<string> checkNetStatusAsync()
        {
            return base.Channel.checkNetStatusAsync();
        }
        
        public System.Threading.Tasks.Task<string> OfflineDataUploadAsync(string M_SN, string M_RESULT, string M_USERNO, string M_MACHINENO, string M_ERROR, string M_ITEMVALUE)
        {
            return base.Channel.OfflineDataUploadAsync(M_SN, M_RESULT, M_USERNO, M_MACHINENO, M_ERROR, M_ITEMVALUE);
        }
        
        public System.Threading.Tasks.Task<string> AddGongBoardAsync(string GroupInfo)
        {
            return base.Channel.AddGongBoardAsync(GroupInfo);
        }
        
        public System.Threading.Tasks.Task<string> LoginCheckAsync(string loginInfo)
        {
            return base.Channel.LoginCheckAsync(loginInfo);
        }
        
        public System.Threading.Tasks.Task<string> MaterialControlAsync(string modelStr)
        {
            return base.Channel.MaterialControlAsync(modelStr);
        }
        
        public System.Threading.Tasks.Task<string> InStationCheckAsync(string modelStr)
        {
            return base.Channel.InStationCheckAsync(modelStr);
        }
        
        public System.Threading.Tasks.Task<string> OutStationCheckDataAsync(string modelStr)
        {
            return base.Channel.OutStationCheckDataAsync(modelStr);
        }
        
        public System.Threading.Tasks.Task<string> SubProductBindingAsync(string modelStr)
        {
            return base.Channel.SubProductBindingAsync(modelStr);
        }
        
        public System.Threading.Tasks.Task<string> SubProductBindingCheckAsync(string modelStr)
        {
            return base.Channel.SubProductBindingCheckAsync(modelStr);
        }
        
        public System.Threading.Tasks.Task<string> ProductBindingAsync(string modelStr)
        {
            return base.Channel.ProductBindingAsync(modelStr);
        }
        
        public System.Threading.Tasks.Task<string> SidePanelMountingMoreAsync(string modelStr)
        {
            return base.Channel.SidePanelMountingMoreAsync(modelStr);
        }
        
        public System.Threading.Tasks.Task<string> FittingBindingAsync(string modelStr)
        {
            return base.Channel.FittingBindingAsync(modelStr);
        }
        
        public System.Threading.Tasks.Task<string> FittingUnBindingAsync(string modelStr)
        {
            return base.Channel.FittingUnBindingAsync(modelStr);
        }
        
        public System.Threading.Tasks.Task<string> GetBoardBarcodeAsync(string modelStr)
        {
            return base.Channel.GetBoardBarcodeAsync(modelStr);
        }
        
        public System.Threading.Tasks.Task<string> CellGroupCheckAsync(string modelStr)
        {
            return base.Channel.CellGroupCheckAsync(modelStr);
        }
        
        public System.Threading.Tasks.Task<string> CellGroupLinkCheckAsync(string cell_sn)
        {
            return base.Channel.CellGroupLinkCheckAsync(cell_sn);
        }
        
        public System.Threading.Tasks.Task<string> CheckPackSNBeforeBindAndConversionAsync(string M_PRODUCT_SN, string M_MO)
        {
            return base.Channel.CheckPackSNBeforeBindAndConversionAsync(M_PRODUCT_SN, M_MO);
        }
        
        public System.Threading.Tasks.Task<string> CollectFixureUseTimesAsync(string M_MACHINENO)
        {
            return base.Channel.CollectFixureUseTimesAsync(M_MACHINENO);
        }
        
        public System.Threading.Tasks.Task<string> DelSNAsync(string M_SN, string M_EMP_NO, string M_EMP_PWD)
        {
            return base.Channel.DelSNAsync(M_SN, M_EMP_NO, M_EMP_PWD);
        }
        
        public System.Threading.Tasks.Task<string> CellBatchInsertDataAsync(PTOMESWebService.CellBatchInsertDataDT dt, string table_name, int batch_count, string sqlconn)
        {
            return base.Channel.CellBatchInsertDataAsync(dt, table_name, batch_count, sqlconn);
        }
        
        public System.Threading.Tasks.Task<string> AutoCapacityAsync(string GroupInfo)
        {
            return base.Channel.AutoCapacityAsync(GroupInfo);
        }
        
        public System.Threading.Tasks.Task<string> BarcodeConversionAsync(string M_PRODUCT_SN, string M_CUSTOMER_SN, string M_MO)
        {
            return base.Channel.BarcodeConversionAsync(M_PRODUCT_SN, M_CUSTOMER_SN, M_MO);
        }
        
        public System.Threading.Tasks.Task<string> BatchInsertDataAsync(PTOMESWebService.BatchInsertDataDT dt, string table_name, int batch_count, string sqlconn)
        {
            return base.Channel.BatchInsertDataAsync(dt, table_name, batch_count, sqlconn);
        }
        
        public System.Threading.Tasks.Task<string> GetCellGroupPackAsync(string pack_sn)
        {
            return base.Channel.GetCellGroupPackAsync(pack_sn);
        }
        
        public System.Threading.Tasks.Task<string> GetFluidLossAsync(string strBattrrySN)
        {
            return base.Channel.GetFluidLossAsync(strBattrrySN);
        }
        
        public System.Threading.Tasks.Task<PTOMESWebService.GetOCV3Response> GetOCV3Async(PTOMESWebService.GetOCV3Request request)
        {
            return base.Channel.GetOCV3Async(request);
        }
        
        public System.Threading.Tasks.Task<string> GetPDAInfoAsync(string PDAInfo)
        {
            return base.Channel.GetPDAInfoAsync(PDAInfo);
        }
        
        public System.Threading.Tasks.Task<string> GetProductEndDateAsync(string product_sn)
        {
            return base.Channel.GetProductEndDateAsync(product_sn);
        }
        
        public System.Threading.Tasks.Task<string> GetProductSNAsync(string BATTERIESNO)
        {
            return base.Channel.GetProductSNAsync(BATTERIESNO);
        }
        
        public System.Threading.Tasks.Task<string> GetProductTestDatasAsync(string lastFlag, string product_sn, string testitems)
        {
            return base.Channel.GetProductTestDatasAsync(lastFlag, product_sn, testitems);
        }
        
        public System.Threading.Tasks.Task<PTOMESWebService.GetSqlDataConnResponseGetSqlDataConnResult> GetSqlDataConnAsync(string sql, string conn)
        {
            return base.Channel.GetSqlDataConnAsync(sql, conn);
        }
        
        public System.Threading.Tasks.Task<string> HR_UserInfoAsync(string str)
        {
            return base.Channel.HR_UserInfoAsync(str);
        }
        
        public System.Threading.Tasks.Task<string> HWInterfaceTestAsync(string M_MACHINENO, string M_PRODUCT_SN, string M_MO, string M_EMP, string M_KP_ITEMSN_ALL, string M_ITEMVALUE, string M_RESULT, string M_ERROR)
        {
            return base.Channel.HWInterfaceTestAsync(M_MACHINENO, M_PRODUCT_SN, M_MO, M_EMP, M_KP_ITEMSN_ALL, M_ITEMVALUE, M_RESULT, M_ERROR);
        }
        
        public System.Threading.Tasks.Task<string> OfflineDataAsync(string M_SN, string M_RESULT, string M_USERNO, string M_MACHINENO, string M_ERROR, string M_ITEMVALUE)
        {
            return base.Channel.OfflineDataAsync(M_SN, M_RESULT, M_USERNO, M_MACHINENO, M_ERROR, M_ITEMVALUE);
        }
        
        public System.Threading.Tasks.Task<string> SMTImageUpload_XRAYAsync(string filename, string img_path)
        {
            return base.Channel.SMTImageUpload_XRAYAsync(filename, img_path);
        }
        
        public System.Threading.Tasks.Task<string> TestDataDimensionAsync(string M_SN, string M_RESULT, string M_USERNO, string M_MACHINENO, string M_ERROR, string M_ITEMVALUE, string M_MO, string M_GROUP_CODE, string M_LOT)
        {
            return base.Channel.TestDataDimensionAsync(M_SN, M_RESULT, M_USERNO, M_MACHINENO, M_ERROR, M_ITEMVALUE, M_MO, M_GROUP_CODE, M_LOT);
        }
        
        public System.Threading.Tasks.Task<string> WeldInputAsync(string M_SN, string M_MO, string M_USERNO, string M_MACHINENO)
        {
            return base.Channel.WeldInputAsync(M_SN, M_MO, M_USERNO, M_MACHINENO);
        }
        
        public System.Threading.Tasks.Task<string> getSystemTimeAsync()
        {
            return base.Channel.getSystemTimeAsync();
        }
        
        public System.Threading.Tasks.Task<string> UnBindDingTrayAsync(string trayNo, string userCode)
        {
            return base.Channel.UnBindDingTrayAsync(trayNo, userCode);
        }
        
        public System.Threading.Tasks.Task<string> BindDingTrayAsync(string jsonData)
        {
            return base.Channel.BindDingTrayAsync(jsonData);
        }
        
        public System.Threading.Tasks.Task<string> CheckTrayValidAsync(string trayNo)
        {
            return base.Channel.CheckTrayValidAsync(trayNo);
        }
        
        public System.Threading.Tasks.Task<string> ProducdtUnBindingAsync(string jsonData)
        {
            return base.Channel.ProducdtUnBindingAsync(jsonData);
        }
        
        public System.Threading.Tasks.Task<string> CellGroupUnBindingAsync(string trayNo)
        {
            return base.Channel.CellGroupUnBindingAsync(trayNo);
        }
        
        public System.Threading.Tasks.Task<string> GetFormulaInfoAsync(string modelStr)
        {
            return base.Channel.GetFormulaInfoAsync(modelStr);
        }
        
        public System.Threading.Tasks.Task<string> GetGroupNameAsync(string productSnList)
        {
            return base.Channel.GetGroupNameAsync(productSnList);
        }
        
        public System.Threading.Tasks.Task<string> MoNumberAndGroupTestAsync(string M_MACHINCENO, string M_EMP, string CellSn, string ProductSn, string GroupName, string MoNumber)
        {
            return base.Channel.MoNumberAndGroupTestAsync(M_MACHINCENO, M_EMP, CellSn, ProductSn, GroupName, MoNumber);
        }
        
        public System.Threading.Tasks.Task<string> CellGroupLink1Async(string CellInfo)
        {
            return base.Channel.CellGroupLink1Async(CellInfo);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MESInterfaceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.MESInterfaceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MESInterfaceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://pmesapi.sunwoda-evb.com/MESInterface.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.MESInterfaceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://pmesapi.sunwoda-evb.com/MESInterface.asmx");
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            MESInterfaceSoap,
            
            MESInterfaceSoap12,
        }
    }
}
