<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Mappings\EntityMappingConfig.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="Mapster" Version="7.4.0" />
    <PackageReference Include="SqlSugarCore" Version="5.1.4.198" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HTHIUM.Core\HTHIUM.Core.csproj" />
    <ProjectReference Include="..\HTHIUM.Logging\HTHIUM.Logging.csproj" />
    <ProjectReference Include="..\HTHIUM.Tool\HTHIUM.Tool.csproj" />
  </ItemGroup>

</Project>
